# Generated by Django 3.2.25 on 2024-05-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='caseshape',
            name='case_shape_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='caseshape',
            name='case_shape_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='name_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='gender_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='gender_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='glassfeature',
            name='glass_feature_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='glassfeature',
            name='glass_feature_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mechanism',
            name='mechanism_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mechanism',
            name='mechanism_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='straptype',
            name='strap_type_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='straptype',
            name='strap_type_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='style_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='style_en',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
